please-scan-api:
  pods:
    replicas: 1

    resources:
      limits:
        cpu: 300m
        memory: 350Mi
      requests:
        cpu: 150m
        memory: 100Mi

    env:
      # To solve ulimit(128) issue
      - name: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"

      - name: ASPNETCORE_ENVIRONMENT
        value: "Production"

      - name: IsDev
        value: "false"

      - name: PostgreSQL__Host
        value: "postgresql-please-scan"

      - name: PostgreSQL__Database
        value: "please-scan"

      - name: PostgreSQL__User
        value: "postgres"

      - name: PostgreSQL__Password
        valueFrom:
          secretKeyRef:
            name: please-scan-postgres-secret
            key: adminPasswordKey
            optional: false
